const ChildDetails = [{
    id: 0,
    name: "CH-1234",
    parentName: "Usama",
    parentCNIC: "4220104689545",
    contactNo: "0312-2410541",
    address: "15-C Modal Town, Lahore",
    dateOfBirth: "03-02-1997",
    gender: "Male",
    birthPlace: "Lahore, Pakistan",
    vaccination: {
        Diphteria: "1",
        Polio: "0",
        Homophiles: "1",
        Rota_Virus: "0",
        Measles: "0",
        Hepatitus_A: "0",
        Hepatitus_B: "1",
        Papilloma_Virus: "0",
        Influenze: "0",
    }

},
{
    id: 1,
    name: "CH-1235",
    parentName: "Usama",
    parentCNIC: "4220104689545",
    contactNo: "0313-2311241",
    address: "14-E Modal Town, Lahore",
    dateOfBirth: "03-02-1989",
    gender: "Male",
    birthPlace: "Lahore, Pakistan.",
    vaccination: {
        Diphteria: "1",
        Polio: "0",
        Homophiles: "1",
        Rota_Virus: "0",
        Measles: "0",
        Hepatitus_A: "0",
        Hepatitus_B: "1",
        Papilloma_Virus: "0",
        Influenze: "0",
    }
},
{
    id: 2,
    name: "CH-1236",
    parentName: "Usama",
    parentCNIC: "4220104689545",
    contactNo: "0313-2311241",
    address: "14-E Modal Town, Lahore",
    dateOfBirth: "03-02-1989",
    gender: "Male",
    birthPlace: "Lahore, Pakistan.",
    vaccination: {
        Diphteria: "1",
        Polio: "0",
        Homophiles: "1",
        Rota_Virus: "0",
        Measles: "0",
        Hepatitus_A: "0",
        Hepatitus_B: "1",
        Papilloma_Virus: "0",
        Influenze: "0",
    }
},
{
    id: 3,
    name: "CH-1237",
    parentName: "Usama",
    parentCNIC: "4220104689545",
    contactNo: "0313-2311241",
    address: "14-E Modal Town, Lahore",
    dateOfBirth: "03-02-1989",
    gender: "Male",
    birthPlace: "Lahore, Pakistan.",
    vaccination: {
        Diphteria: "1",
        Polio: "0",
        Homophiles: "1",
        Rota_Virus: "0",
        Measles: "0",
        Hepatitus_A: "0",
        Hepatitus_B: "1",
        Papilloma_Virus: "0",
        Influenze: "0",
    }
},
{
    id: 4,
    name: "CH-1238",
    parentName: "Usama",
    parentCNIC: "4220104689545",
    contactNo: "0313-2311241",
    address: "14-E Modal Town, Lahore",
    dateOfBirth: "03-02-1989",
    gender: "Male",
    birthPlace: "Lahore, Pakistan.",
    vaccination: {
        Diphteria: "1",
        Polio: "0",
        Homophiles: "1",
        Rota_Virus: "0",
        Measles: "0",
        Hepatitus_A: "0",
        Hepatitus_B: "1",
        Papilloma_Virus: "0",
        Influenze: "0",
    }
},
{
    id: 5,
    name: "CH-1239",
    parentName: "Usama",
    parentCNIC: "4220104689545",
    contactNo: "0313-2311241",
    address: "14-E Modal Town, Lahore",
    dateOfBirth: "03-02-1989",
    gender: "Male",
    birthPlace: "Lahore, Pakistan.",
    vaccination: {
        Diphteria: "1",
        Polio: "0",
        Homophiles: "1",
        Rota_Virus: "0",
        Measles: "0",
        Hepatitus_A: "0",
        Hepatitus_B: "1",
        Papilloma_Virus: "0",
        Influenze: "0",
    }
}
]

export default ChildDetails;